# Generated by Django 3.0.4 on 2020-03-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
    ]
