# Generated by Django 3.0.4 on 2020-04-05 22:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20200329_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
