# Generated by Django 3.0.4 on 2020-05-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'true'), ('False', 'false')], default='New', max_length=10),
        ),
    ]
