# Generated by Django 3.0.4 on 2020-05-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_auto_20200502_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
