# Generated by Django 3.0.6 on 2020-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0016_auto_20200516_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'true'), ('False', 'false')], max_length=10),
        ),
    ]
