# Generated by Django 3.0.4 on 2020-04-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200406_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
