# Generated by Django 3.0.4 on 2020-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='note',
            new_name='message',
        ),
    ]
