# Generated by Django 3.0.4 on 2020-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactform_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
