# Generated by Django 3.0.6 on 2020-05-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('True', 'true'), ('False', 'false')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('True', 'true'), ('False', 'false')], max_length=10, null=True),
        ),
    ]
